# This is a basic workflow to help you get started with Actions

name: build test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  #build:
  test:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Git repository
      uses: actions/checkout@v2
    # - name: Install TeX Live
    #   run: bash .github/workflows/install-tl.sh

    # Runs a single command using the runners shell
    # - name: Test thesis
    #   run: |
    #     export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
    #     latexmk -xelatex -synctex=1 -shell-escape -interaction=nonstopmode -file-line-error MasterTemplate.tex

    # Runs a set of commands using the runners shell
    #- name: Test doc
    #  run: |
    #    export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
    #    make doc

    # use action with full Texlive installed
    - name: Github Action for LaTeX
      uses: xu-cheng/texlive-action/small@v1
      with:
        run: |
          tlmgr version
          echo ###XETEX_PKGS###
          tlmgr install fontname fontspec l3packages xetex
          echo ###CTEX_PKGS###
          tlmgr install cjk ctex environ ms trimspaces ulem xecjk zhnumber
          echo ###HYPERREF_PKGS###
          tlmgr install bitset letltxmacro pdfescape pdflscape
          echo ###NOMENCL_PKGS###
          tlmgr install nomencl koma-script xkeyval

          echo ###BIN_PKGS###
          tlmgr install latexmk l3build
          echo ###REQUIRED_PKGS###
          tlmgr install amsmath amsfontss
          echo ###EXTRA_PKGS###
          tlmgr install siunitx zhlineskip
          echo ###DOC_PKGS###
          tlmgr install booktabs listings xcolor

          latexmk -xelatex -synctex=1 -shell-escape -interaction=nonstopmode -file-line-error MasterTemplate.tex
